apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-deployment
  labels:
    app: taxi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi
  template:
    metadata:
      labels:
        app: taxi
    spec:
      containers:
        - name: taxi
          image: zhilnikova/mlops-otus-project:21dd32f44d24181ad289541be12a5dc1326a7fc6
          ports:
            - containerPort: 8000