version: "3.7"
services:
  # jupyter:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.jupyter
  #   image: otus-maas:jupyter
  #   container_name: otus-maas-jupyter
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebooks:/app/notebooks
  #   command: ["bash", "scripts/entrypoint-jupyter.sh"]
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: otus-maas:dev
    container_name: otus-maas-dev
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./src:/app/src
    command: ["bash", "scripts/entrypoint-dev.sh"]